copyright: Copyright &copy; 2025 - {current_year}
docs_dir: blog
edit_uri: edit/main/blog/
repo_name: sanderdelden/blog.sanderdelden.nl
repo_url: https://github.com/sanderdelden/blog.sanderdelden.nl
site_author: Sander van Delden
site_description: test
site_name: Sander's network (automation) blog
site_url: https://blog.sanderdelden.nl

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  annotate:
    json: [.s2]
    bash: [.s2]
  generator: false
  social:
  - icon: fontawesome/brands/square-linkedin
    link: https://www.linkedin.com/in/sander-van-delden/
  - icon: fontawesome/brands/square-github
    link: https://github.com/sanderdelden

extra_javascript:
- javascripts/extra.js

hooks:
- blog/hooks/hooks.py

markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink:
    normalize_issue_symbols: true
    repo_url_shorthand: true
    repo: mkdocs-material
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- toc:
    permalink: true

nav:
- Blog:
  - index.md
- Tags:
  - tags.md

plugins:
- blog:
    blog_dir: .
    post_url_date_format: yyyy
    pagination_per_page: 5
- glightbox
- minify:
    minify_html: true
- search
- tags

theme:
  custom_dir: blog/overrides
  favicon: assets/images/favicon.svg
  features:
  - announce.dismiss
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.prune
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - navigation.instant
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  font:
    text: Google Sans
    code: Fira Mono
  icon:
    logo: fontawesome/solid/ethernet
    repo: fontawesome/brands/square-github
    edit: material/file-edit-outline
  language: en
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: white
    accent: cyan
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: cyan
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
