name: CI

on: [push, workflow_dispatch]  # yamllint disable-line rule:truthy

jobs:
  lint:
    name: Use super-linter to lint all code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Lint code base
      uses: super-linter/super-linter@v8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINTER_RULES_PATH: .
        MARKDOWN_CONFIG_FILE: .markdownlint.yml
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_MARKDOWN: true
        VALIDATE_YAML: true
        YAML_CONFIG_FILE: .yamllint.yml
        YAML_ERROR_ON_WARNING: true

  build:
    name: Build site files with MkDocs
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Set up UV
      uses: astral-sh/setup-uv@v6
    - name: Install dependencies
      run: uv sync
    - name: Build
      run: uv run mkdocs build --clean --strict
      env:
        GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
    - name: Upload site artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: site/

  deploy:
    name: Deploy to Cloudflare pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      deployments: write
    steps:
    - name: Download site artifacts
      uses: actions/download-artifact@v5
      with:
        name: site
        path: site/
    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy site/ --project-name=blog-sanderdelden-nl
